In [1]:
import numpy as np
from math import sqrt
from numpy.linalg import inv as inv

view_matrix = [
    [
        -911.1166503675031,
        248.36954810208073,
        -18.926058477425673,
        -167.8990857473499
    ],
    [
        -143.3053098339586,
        -155.6642549692365,
        -711.1451153584082,
        -101.23306697418491
    ],
    [
        0.0,
        0.0,
        0.0,
        1.0
    ],
    [
        -0.8239435046107771,
        -0.5647533532572663,
        0.0465915926090965,
        -0.2721327964058732
    ]
]

view_matrix = np.array([view_matrix[0], view_matrix[1], view_matrix[3]])


aat = np.matmul(view_matrix, np.transpose(view_matrix))

aat = aat/(aat[2, 2])
print(aat)

cx = aat[0, 2]
cy = aat[1, 2]

print(cx, cy)
# print(aat[0, 1])

fx = sqrt(aat[0, 0] - cx * cx)
fy = sqrt(aat[1, 1] - cy * cy)
print(fx, fy)

[[8.56909731e+05 1.13924855e+05 6.10070602e+02]
 [1.13924855e+05 5.22079978e+05 1.86585048e+02]
 [6.10070602e+02 1.86585048e+02 1.00000000e+00]]
610.0706015452691 186.5850479572041
696.2209363740762 698.0444095616135


In [4]:
import math

fys = [237.4, 474.8, 949.6]

TRIANGLE_SIGN_HEIGHT = 0.9 * math.cos(math.pi / 6)

TRAFFIC_SIGN_HEIGHTS = [0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.6,
                        0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.6,
                        TRIANGLE_SIGN_HEIGHT, # construction site
                        0.9, # stop
                        TRIANGLE_SIGN_HEIGHT, # yield
                        0.6,0.6,0.6,0.6,0.6]

for tfh in TRAFFIC_SIGN_HEIGHTS:
    print([tfh*fy/5 for fy in fys])


[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[37.00699755451664, 74.01399510903327, 148.02799021806655]
[42.732, 85.464, 170.928]
[37.00699755451664, 74.01399510903327, 148.02799021806655]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
[28.488, 56.976, 113.952]
